name = "DK's Adventures"
author = "Daniel Kindl"
version = "0.1.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "442b7ae4b172a7e4d549b10cad4209f2c3fee563529727b02b372d26c26bc4ad"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
