name = "DK's Adventures"
author = "Daniel Kindl"
version = "0.1.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79c21ccd856a13c66303222cfc1be1581425113759512a2fe63c11ce9f4f7ec4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
