name = "DK's Adventures"
author = "Daniel Kindl"
version = "0.1.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fa695b1266b9c5ceb2764476f0486bf4de01b70580bb24c8ed58d506c7c5467"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
